# This file dictates the settings the router should use when running
supergraph:
  listen: 127.0.0.1:4000
include_subgraph_errors:
  all: true
telemetry:
  instrumentation:
    spans:
      mode: spec_compliant
headers:
  all:
    request:
      - propagate:
          named: "Authorization"

subscription:
  enabled: true
  mode:
    callback:
      public_url: http://127.0.0.1:4000/callback
      listen: 127.0.0.1:4000
      path: /callback
      heartbeat_interval: 5s
      subgraphs:
        - messages
